version: '3.8'

services:
  web:
    build: .
    container_name: josemoreupeso-es
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: php -S 0.0.0.0:8080 -t public public/index.php
    working_dir: /app
